[package]
name = "star-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy.git"
rev = "48e9dc1"

#[dependencies.bevy_hanabi]
#git = "https://github.com/LarsDu/bevy_hanabi.git"
#branch = "larsdu/update_for_0.9"
#rev = "82d9423"

[workspace]
resolver ="2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
